TERMOS_SETOR_AUDIOVISUAL = [
    "audiovisual",
    "cinema",
    "filme",
    "gravação",
    "fotografia",
    "direção de arte",
    "cena",
    "ator",
    "atriz",
    "personagem",
    "personagens",
    "film",
    "films",
    "movie",
    "screen",
    "screenplay",
    "roteiro",
    "documentary",
    "documentário",
    "documentario",
    "animation",
    "animação",
    "animacao",
    "anime",
    "desenho",
    "desenho animado",
    "series",
    "série",
    "serie",
    "tv",
    "televisão",
    "televisao",
    "novela",
    "novela vertical",
    "mini-série",
    "minisérie",
    "video",
    "vídeo",
    "curta",
    "curta-metragem",
    "curta metragem",
    "short film",
    "filmes curtos"
    "longa",
    "longa-metragem",
    "longa metragem",
    "feature film",
    "documentário de longa",
    "documentary feature",
    "videoarte",
    "videoart",
    "videoclipe",
    "clip",
    "serial",
    "seriado",
    "episódio",
    "episodio",
    "webserie",
    "websérie",
    "coprodução",
    "coproducao",
    "co-production",
    "coproduction",
    "distribution",
    "distribuição",
    "distribuicao",
    "exhibition",
    "exibição",
    "exibicao",
    "post-production",
    "postproduction",
    "pós-produção",
    "pos-producao",
    "finalização",
    "finalizacao",
    "film festival",
    "festival de cinema",
    "mostra de cinema",
    "mostra de animação",
    "festival de animação"
    "film market",
    "encontros audiovisuais"
    "feiras audiovisuais"
    "set de filmagem"
    "industria do cinema"
    "bastidores"
    "behind the scenes"
    "industry",
    "new media",
    "immersive",
    "xr",
    "vr",
    "ar",
    "games",
    "jogos digitais",
    "transmedia",
    "transmídia",
    "media art"
]

TERMOS_OPORTUNIDADE = [
    "edital",
    "edital público",
    "edital publico",
    "chamada",
    "chamada pública",
    "chamada publica",
    "convocatória",
    "convocatoria",
    "seleção",
    "selecao",
    "inscrição",
    "inscricao",
    "open call",
    "call",
    "call for entries",
    "call for proposals",
    "application",
    "applications",
    "apply now",
    "submit",
    "submit your project",
    "grant",
    "grants",
    "funding",
    "fund",
    "financial support",
    "apoio financeiro",
    "fomento",
    "incentive",
    "opportunity",
    "opportunities",
    "festival",
    "mostra",
    "screening",
    "market",
    "film market",
    "industry forum",
    "forum",
    "pitch",
    "pitching",
    "one-to-one",
    "1-to-1",
    "lab",
    "laboratory",
    "laboratório",
    "laboratorio",
    "workshop",
    "training",
    "mentoria",
    "mentorship",
    "residency",
    "residencies",
    "residência",
    "residencia",
    "fellowship",
    "scholarship",
    "award",
    "prize",
    "prêmio",
    "premio",
    "incubator",
    "incubadora",
    "accelerator",
    "aceleração",
    "aceleracao",
    "co-production market",
    "coproduction market",
    "cofinancing",
    "distribution support",
    "circulation support"
]

TERMOS_RUIDO = [
    "login",
    "menu",
    "newsletter",
    "privacy",
    "privacy policy",
    "cookies",
    "cookie policy",
    "feedback",
    "language",
    "terms",
    "terms of use",
    "guide",
    "funding guide",
    "case studies",
    "about this page",
    "learn more",
    "read more",
    "discover more",
    "skip to main content",
    "breadcrumb",
    "search",
    "contact",
    "contato",
    "facebook",
    "instagram",
    "linkedin",
    "youtube",
    "whatsapp",
    "home",
    "homepage",
    "quem somos",
    "about us",
    "carreiras",
    "careers",
    "jobs",
    "vacancies",
    "relatório anual",
    "relatorio anual",
    "annual report"
]